### ISSUE TITLE
React component skeleton

### ISSUE THREAD

**Issue by qmmr** [6to5/6to5-sublime#21]
I've been using different 'flavor' of React.createClass
```jsx
'use strict';

import React from 'react';

export default React.createClass({
	render() {
		return ();
	}
})
```

I'd like to update the snippets with this minimalistic approach of exporting the component + adding the `'use strict';` statement. What do you think?

**Comment by zertosh** [comment]
Hey @qmmr,  `6to5` already adds the strict mode invocation since [ES6 modules are always in strict mode](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-strict-mode-code).

As for calling `React.createClass` right on the `export default`, that presents a problem if you want to add properties right on the constructor. I know you have `statics`, but there are a [few things](https://github.com/facebook/react/blob/v0.12.2/src/core/ReactCompositeComponent.js#L327-L391) you're not allowed to specify there that you can still add directly to the constructor.

But maybe I'm wrong? Is there a more compelling reason for the change? When 0.13.0-stable drops, we're going to need another skeleton snippet for bare classes that extend `React.Component`. So maybe we can adopt this change for the old `React.createClass` since it does have `statics`. Thoughts?

**Comment by zertosh** [comment]
wow and you also lose the `displayName` because the transform doesn't know where to get it from.

**Comment by qmmr** [comment]
Hey @zertosh, you're right about strict mode.
I know that you're restricting yourself by using the `shorthand` method of exporting directly, however I feel that often times it's a very quick and elegant way to create a small component. That's why I would propose to have a different snippet to use for this `shorthand` version, something like `rcs (react shorthand component skeleton)`.
That is of course, like you said, until 0.13 is stable.

**Comment by zertosh** [comment]
@qmmr What about `displayName`? By using the short version, you're missing out on getting that automatically by the transpiler.

**Comment by sebmck** [comment]
@zertosh I could possibly add an edgease that uses the basename of the current filename as the `displayName` for `export default React.createClass`.

**Comment by sebmck** [comment]
Done.

**Comment by zertosh** [comment]
Nice @sebmck! @qmmr Want to submit a PR for that snippet?

**Comment by qmmr** [comment]
@sebmck  :+1: 
@zertosh Cool, will do it later today.

**Comment by qmmr** [comment]
[PR](https://github.com/6to5/6to5-sublime/pull/23) submitted.

**Comment by zertosh** [comment]
Fixed by https://github.com/6to5/6to5-sublime/pull/23
