### ISSUE TITLE
Rename syntax name

### ISSUE THREAD

**Issue by Dashed** [6to5/6to5-sublime#5]
> Then Syntax -> Open all with current extension as... -> `JavaScript JSX`.

IMO, I think `JavaScript JSX` should be renamed to something else (maybe `JavaScript 6to5`?). JSX isn't the only thing that has highlighting support, but generally/ideally anything that 6to5 supports syntactically (e.g. ES7+).

**Comment by Dashed** [comment]
Also, the name nearly confused me because `sublime-react` also have a similar name: https://github.com/reactjs/sublime-react/blob/4dba5d41b8174df35af00299fcb2986464a747d5/syntax/jsx/tmLanguage/JavaScript%20(JSX).JSON-tmLanguage#L2

**Comment by zertosh** [comment]
Yeah, I'm totally cool with this. FYI: The one thing we _can't_ change is the filename, otherwise SublimeLinter-jsxhint might not work. The lowercased `tmLanguage` filename is the syntax's name. And SublimeLinter-jsxhint only has [`'jsx', 'javascript_jsx', 'javascript (jsx)'](https://github.com/SublimeLinter/SublimeLinter-jsxhint/blob/f991f90/linter.py#L23) listed.

Can I get another :+1: for the rename?

**Comment by gpbl** [comment]
:+1:

**Comment by STRML** [comment]
Feel free to rename it, please just respond to this ticket with the target rename and I will add it to sublimelinter-jsxhint.

**Comment by zertosh** [comment]
Done. Renamed to `JavaScript 6to5`

**Comment by STRML** [comment]
SublimeLinter-JSXHint `1.1.0` now has support for this name.
